//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ClientProject
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class directions
    {
        [Required]
        public int Id { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Dirección")]
        public string direction { get; set; }
        [Required(ErrorMessage = "El campo es obligatorio")]
        [Display(Name = "Cliente")]
        public Nullable<int> Id_client { get; set; }
    
        public virtual client client { get; set; }
    }
}
